services:
  esim:
    image: "nginx:alpine"
    container_name: "esim"
    ports:
      - "8080:80"
    restart: "always"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./app:/app"
    depends_on:
      - "api"
    networks:
      - "esim"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "api"
    restart: "always"
    volumes:
      - "./data:/app/data"   # общая папка для истории
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    networks:
      - "esim"

networks:
  esim:
    driver: bridge
